version: '3.8'

services:
  # C# Backend API
  backend-api:
    build:
      context: ./backend
      dockerfile: ../docker/dockerfiles/Dockerfile.backend
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/smartbin.db
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    networks:
      - smartbin-network
    restart: unless-stopped

  # Python services
  python-services:
    build:
      context: ./python-services
      dockerfile: ../docker/dockerfiles/Dockerfile.python
    ports:
      - "8001:8001"
      - "8002:8002"
    environment:
      - MODEL_PATH=/app/models/trash_classifier_v3_93_accuracy_4mp.keras
      - CAMERA_INDEX=0
      - ARDUINO_PORT=/dev/ttyUSB0
      - BACKEND_URL=http://backend-api:5000/classification-hub
    volumes:
      - ./models:/app/models
      - ./logs:/app/logs
      - /dev/video0:/dev/video0
      - /dev/ttyUSB0:/dev/ttyUSB0
    devices:
      - /dev/video0:/dev/video0
      - /dev/ttyUSB0:/dev/ttyUSB0
    networks:
      - smartbin-network
    restart: unless-stopped
    depends_on:
      - backend-api

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/dockerfiles/Dockerfile.frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
      - REACT_APP_WS_URL=ws://localhost:5000
    depends_on:
      - backend-api
    networks:
      - smartbin-network
    restart: unless-stopped

networks:
  smartbin-network:
    driver: bridge
