// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartRecyclingBin.Data;

#nullable disable

namespace SmartRecyclingBin.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250902155336_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("SmartRecyclingBin.Models.ClassificationResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CandidatesCount")
                        .HasColumnType("INTEGER");

                    b.Property<double>("CnnConfidence")
                        .HasColumnType("REAL");

                    b.Property<string>("CnnPredictedClass")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("CnnStage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DetectionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisposalLocation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FinalClassification")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double>("FinalConfidence")
                        .HasColumnType("REAL");

                    b.Property<bool>("HasImage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<double>("HumidityPercent")
                        .HasColumnType("REAL");

                    b.Property<string>("ImageBase64")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ImageCaptureTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageDimensions")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageFormat")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("jpeg");

                    b.Property<long?>("ImageSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("IrTransparency")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsFlexible")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMetalDetected")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMoist")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOverridden")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTransparent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OverriddenBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("OverrideClassification")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("OverrideReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("OverrideTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("OverrideUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessingPipeline")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<double>("ProcessingTimeMs")
                        .HasColumnType("REAL");

                    b.Property<string>("Reasoning")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<double>("TemperatureCelsius")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("ValidationResults")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<double>("WeightGrams")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("DetectionId");

                    b.HasIndex("FinalClassification");

                    b.HasIndex("HasImage");

                    b.HasIndex("IsOverridden");

                    b.HasIndex("Timestamp");

                    b.ToTable("ClassificationResults");
                });

            modelBuilder.Entity("SmartRecyclingBin.Models.SystemAlert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Component")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolvedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.HasKey("Id");

                    b.HasIndex("IsResolved");

                    b.HasIndex("Severity");

                    b.HasIndex("Timestamp");

                    b.ToTable("SystemAlerts");
                });

            modelBuilder.Entity("SmartRecyclingBin.Models.SystemHealthMetrics", b =>
                {
                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<double>("AccuracyRate")
                        .HasColumnType("REAL");

                    b.Property<bool>("ArduinoConnected")
                        .HasColumnType("INTEGER");

                    b.Property<double>("AvgProcessingTimeMs")
                        .HasColumnType("REAL");

                    b.Property<bool>("CameraConnected")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClassificationCounts")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("CnnServiceHealthy")
                        .HasColumnType("INTEGER");

                    b.Property<double>("CpuUsagePercent")
                        .HasColumnType("REAL");

                    b.Property<bool>("ExpertSystemHealthy")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MemoryUsageMB")
                        .HasColumnType("REAL");

                    b.Property<double>("SystemUptime")
                        .HasColumnType("REAL");

                    b.Property<int>("TotalItemsProcessed")
                        .HasColumnType("INTEGER");

                    b.HasKey("Timestamp");

                    b.ToTable("HealthMetrics");
                });
#pragma warning restore 612, 618
        }
    }
}
